BEGIN TRANSACTION;
INSERT INTO "Status" VALUES (200,'Active');
INSERT INTO "Status" VALUES (201,'Inactive');
INSERT INTO "Status" VALUES (203,'In Maintenance');
INSERT INTO "Artworks" VALUES (2201,'The Starry Night',1101,1889,1,100,200);
INSERT INTO "Artworks" VALUES (2202,'Cafe Terrace At Night',1101,1888,1,100,200);
INSERT INTO "Artworks" VALUES (2203,'Vase With 12 Sunflowers',1101,1889,1,100,201);
INSERT INTO "Artworks" VALUES (2204,'Mona Lisa',1102,1503,2,100,200);
INSERT INTO "Artworks" VALUES (2205,'Impression, Sunrise',1103,1872,3,100,200);
INSERT INTO "Artworks" VALUES (2206,'Water Lilies',1103,1906,3,100,201);
INSERT INTO "Artworks" VALUES (2207,'The Scream',1104,1893,4,101,203);
INSERT INTO "Artworks" VALUES (2208,'The Girl With A Pearl Earring',1105,1665,5,100,203);
INSERT INTO "Artworks" VALUES (2209,'The Snake Charmer',1106,1879,6,103,200);
INSERT INTO "Artworks" VALUES (2210,'The Gleaners',1107,1857,7,103,201);
INSERT INTO "Artworks" VALUES (2211,'In The Rain',1108,1912,8,100,203);
INSERT INTO "Artworks" VALUES (2212,'Dead Deer',1108,1913,4,100,200);
INSERT INTO "Artworks" VALUES (2213,'The Golden Gate',1109,1900,9,104,200);
INSERT INTO "Artworks" VALUES (2214,'Fishing Boats At Capri',1109,1857,10,104,200);
INSERT INTO "Administrator" VALUES (300,'Chris','Lee',100,'01/11/2011','01/11/2011','chris@gmail.com');
INSERT INTO "Administrator" VALUES (301,'Alice','Green',101,'01/11/2015','01/11/2015','Alice@gmail.com');
INSERT INTO "Administrator" VALUES (302,'Yvonne','Stock',103,'01/11/2017','01/11/2020','Yvonne@gmail.com');
INSERT INTO "Administrator" VALUES (303,'Lily','Lee',102,'07/11/2020','08/12/2022','lily@gmail.com');
INSERT INTO "Administrator" VALUES (304,'Susan','Jennings',104,'01/04/2020','05/20/2025','susan@gmail.com');
INSERT INTO "Gallery" VALUES (100,'THE ART INSTITUTE OF CHICAGO','ILLINOIS','1234566000','newcomb@gmail.com');
INSERT INTO "Gallery" VALUES (101,'HILLIGOSS GALLERIES','ILLINOIS','1234567000','hikkigoss@gmail.com');
INSERT INTO "Gallery" VALUES (102,'MEYER GALLERY','UTAH','1234569000','meyer@gmail.com');
INSERT INTO "Gallery" VALUES (103,'THE METROPOLITAN GALLERY OF LAS VEGAS ART MUSEUM','NEVADA','1234568900','metro@gmail.com');
INSERT INTO "Gallery" VALUES (104,'BLUE RAIN GALLERY','NEW MEXICO','1234565000','bluerain@gmail.com');
INSERT INTO "Artists" VALUES (1101,'Vincent Van Gogh',1853,1890,10,'Vincent Willem van Gogh was an extremely prominent Dutch post-Impressionist artist and one of the most important artists of our time. His paintings are notable for their coarse beauty, emotional truthfulness, and usage of bold colour palette. His prolific art had a powerful influence on modern art, especially 20th century painting styles using abstraction, fauvism, and expressionism.');
INSERT INTO "Artists" VALUES (1102,'Leonardo Da Vinci',1452,1519,15,'Leonardo da Vinci is considered to be not only the greatest painter the world has ever seen but also one of the most diversely gifted persons to have ever been born. A skilled draftsman, architect, sculptor, scientist and engineering genius with immense curiosity, scientific abilities and inventiveness, he is regarded by all as being far ahead of his times. One of the greatest creators of Italian High Renaissance art, he is legendary for his mastery over oil painting and the sophisticated techniques of chiaroscuro and sfumato. His “Mona Lisa”, a masterpiece that employs both these techniques with great effect, is without a doubt the world’s most well-known painting.');
INSERT INTO "Artists" VALUES (1103,'Claude Monet',1840,1926,13,'Claude Monet was a 19th century French painter and founder of the French Impressionist painting that revolved around communicating perceptions in front of nature. Along with contemporaries Renoir, Sisley, and Bazille, he formed the core of Impressionist art, a style which he prolifically pursued for most of his painting career. The title of his most famous painting, “Impression, Sunrise” was used to coin the term ‘Impressionism’.');
INSERT INTO "Artists" VALUES (1104,'Edvard Munch',1863,1944,16,'Edvard Munch, the Norwegian artist, is considered to be a key precursor of Expressionism. Closely connected with Symbolism, Munch is best remembered for his imaginative images of angst, isolation, sexuality, denial, and death, many of which mirror his phobic and tragic life. His most famed painting is “The Scream” that is one of the most familiar works in artistic history. Noted for its vigorous style and simple direct approach, Munch’s extensive oeuvre of paintings, engravings, woodcuts and lithographs is regarded as an important force in contemporary graphic art.');
INSERT INTO "Artists" VALUES (1105,'Johannes Vermeer',1632,1675,10,'Johannes Vermeer was a Dutch artist who was well-known for his depictions of domestic middle-class interior scenes. He set a majority of his paintings in his house in Delft, particularly two small rooms with unchanging furniture and different refurbishments, often having the same people, mostly women, as subjects. His subjects also encompassed milkmaids working to affluent merchants ensconced in their luxurious homes. Vermeer’s works typically employed a rich color palette with costly pigments and are considered a study of the 17th century Dutch society.');
INSERT INTO "Artists" VALUES (1106,'Nasreddine Dinet',1861,1929,13,'Nasreddine Dinet was a French orientalist painter and was one of the founders of the Société des Peintres Orientalistes [Society for French Orientalist Painters]. He became so enchanted with North Africa and its culture, that he converted to Islam, and was proficient in Arabic.');
INSERT INTO "Artists" VALUES (1107,'Jean-Francois Millet',1814,1875,13,'Jean-François Millet was a French artist and one of the founders of the Barbizon school in rural France. Millet is noted for his paintings of peasant farmers and can be categorized as part of the Realism art movement. Toward the end of his career he became increasingly interested in painting pure landscapes.');
INSERT INTO "Artists" VALUES (1108,'Franz Marc',1880,1916,11,'Franz Moritz Wilhelm Marc was a German painter and printmaker, one of the key figures of German Expressionism. He was a founding member of Der Blaue Reiter, a journal whose name later became synonymous with the circle of artists collaborating in it');
INSERT INTO "Artists" VALUES (1109,'Albert Bierstadt',1830,1902,14,'Albert Bierstadt is one of the best-known American painters of all times. He belonged to the Hudson River School of painting that was celebrated for its meticulous attention to detail and a romantic representation of life of the American pioneers, and the technique of adding a glowing radiance that was typical of the Luminist style. His depictions of the wilderness scenery of Western America that included national parks and reserves, scenic lakes, frosty glaciers and creatures of the wild, are notable for their colossal sizes and vibrant use of colors, together with the interplay of light and shadow.');
INSERT INTO "Art_movements" VALUES (1,'Post-Impressionism');
INSERT INTO "Art_movements" VALUES (2,'Renaissance');
INSERT INTO "Art_movements" VALUES (3,'Impressionism');
INSERT INTO "Art_movements" VALUES (4,'Expressionism');
INSERT INTO "Art_movements" VALUES (5,'Baroque');
INSERT INTO "Art_movements" VALUES (6,'Orientalism');
INSERT INTO "Art_movements" VALUES (7,'Realism');
INSERT INTO "Art_movements" VALUES (8,'Cubism');
INSERT INTO "Art_movements" VALUES (9,'Luminism');
INSERT INTO "Art_movements" VALUES (10,'Romanticism');
INSERT INTO "Nationality" VALUES (10,'Dutch','Europe');
INSERT INTO "Nationality" VALUES (11,'German','Europe');
INSERT INTO "Nationality" VALUES (12,'North America','Europe');
INSERT INTO "Nationality" VALUES (13,'France','Europe');
INSERT INTO "Nationality" VALUES (14,'America','America');
INSERT INTO "Nationality" VALUES (15,'Italy','Europe');
INSERT INTO "Nationality" VALUES (16,'Norwegian','Europe');
COMMIT;
